### ISSUE TITLE
Build scripts for supporting libraries and executables

### ISSUE THREAD

**Issue by aurieh** [migaku-official/Migaku-Japanese-Addon#27]
#### Nature of issue?

- New feature request

#### New feature details:
It'd be nice to have scripts necessary to build files in `src/support` bundled with this repository, as there are certain platforms current prebuilt binaries don't cover (i.e. non-glibc Linux, the BSDs). I wouldn't mind contributing a set of generic Linux scripts, but I'd like to hear your opinion on the matter before investing what could be a decent amount of effort.

**Comment by LucasMIA** [comment]
Sure, open a pr anytime. We don't support Linux officially but are open to accepting prs from the community!

**Comment by dmgerman** [comment]
I have the feeling that there is no such a thing as scripts to support building the binaries.  binaries seem to be simply copied from add-on to add-on. All Mecab-using add-ons seem to be using the same binaries. the simplest solution to different distros in linux is to symlink the mecab.bin to the distro mecab binary. Extension simply executes the binary and pipes its input and output.

**Comment by dmgerman** [comment]
Look at reading.py to understand how mecab is used

**Comment by KieranMigaku** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
