### ISSUE TITLE
Better morphemizer dict (ipadic-neologd)

### ISSUE THREAD

**Issue by setreadygo** [migaku-official/Migaku-Japanese-Addon#37]
There's a better dictionary for mecab called neologd, although it's quite bulky (1gb vs the 50mb currently bundled dict vs the 250mb ipadic morphman addon).

https://github.com/neologd/mecab-ipadic-neologd

It would solve a lot of accuracy issues with readings that are popping up. Also, even the latest mecab-ipadic is 8 years old (!) while neologd is a new corpus that has been updated as recently as a few weeks ago.

**Comment by LucasMIA** [comment]
Would you be interested in opening a pr about this?

**Comment by jamesrwaugh** [comment]
I've been considering adding this, but not natively due to its size. Would an option to select an alternate MeCab dictionary be suitable? @LucasMIA

**Comment by dmgerman** [comment]
i looked into this. the code is very tied to the format of the Mecab output it uses. It would require several changes to adapt to the extended output of the Ipadic one. The easiest way would be to create a filter that makes Ipadic behave  like the currently used Mecab. This does not have be done inside the extension. It can be drop-in replacement.

**Comment by KieranMigaku** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
