### ISSUE TITLE
Addon conflict with pop-up dictionary

### ISSUE THREAD

**Issue by HadesNinth** [migaku-official/Migaku-Japanese-Addon#50]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Windows 10

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
I've reported this problem on the pop-up dictionary github page before and so far, the problem has been resolved with the MIA Dictionary addon, but not with the MIA Japanese addon.
When the MIA Japanese addon is active, the pop-up dictionary addon will not work.
I hope you can apply the same fix as you did with the MIA Dictionary addon.
Cheers,
Hades.

**Comment by KieranMigaku** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
