### ISSUE TITLE
Generation of Audio and Pitch Graph fields doesn't work with "If Empty"

### ISSUE THREAD

**Issue by MikeMoolenaar** [migaku-official/Migaku-Japanese-Addon#54]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Windows 10
  - Add-on version: latest (0.6.0 I think?)
  - Anki: 2.1.22

**I'm going to open a PR to resolve the issue:**
  - [x] yes
  - [ ] no

**Description:**
Generation of Audio and Pitch Graph fields don't work when set to `If Empty`, even when the target fields are empty.
![image](https://user-images.githubusercontent.com/20370521/83260988-f3883380-a1ba-11ea-8445-8a0cc5b8a1a7.png)

**Comment by IamMeWasTaken** [comment]
So is the issue fixed? Or what is the fix if I can just edit the files myself? Don't really wanna wait till september for the bug to be resolved.

**Comment by MikeMoolenaar** [comment]
Seems like the author of the add-on doesn't look at PR's and issues. I made a PR which contains the fix for this issue, see the [files changes](https://github.com/migaku-official/Migaku-Japanese-Addon/pull/55/files) section so you can edit that file localy.

**Comment by LucasMIA** [comment]
@MikeMoolenaar Actually we are currently in the process of setting up maintainers to help us on GitHub. We plan to try and build a really active community here in the coming months. I apologize for how these repos have been run thus far but know that it's not been because of lack of desire but simply because of lack of sufficient time and resources. We are working on fixing that by getting more collaborators involved with these projects directly. Expect these changes over the next month or so.

**Comment by MikeMoolenaar** [comment]
> @MikeMoolenaar Actually we are currently in the process of setting up maintainers to help us on GitHub. We plan to try and build a really active community here in the coming months. I apologize for how these repos have been run thus far but know that it's not been because of lack of desire but simply because of lack of sufficient time and resources. We are working on fixing that by getting more collaborators involved with these projects directly. Expect these changes over the next month or so.

Ah great to hear!
