### ISSUE TITLE
MIA Japanese Native Audio Generation (F3) Not Working Properly

### ISSUE THREAD

**Issue by mZuks** [migaku-official/Migaku-Japanese-Addon#59]
**Type:**
  - [X ] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Windows 10

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [X ] no

**Description:**
[ Whenever I generate the audio for a word, either using the F3 hotkey or clicking on the button, although the syntax appears, no audio plays on my card. If, however, I manually copy and paste the mp3 into the field, it works just fine, which indicates that something regarding the add-on's function is off. It's worth mentioning that this doesn't happen to all words, but is happens to most of them, about 80%. Needless to say, I do have the accentAudio folder placed inside the user_files folder, and the audio files for the words I've tried generating are included. My Anki version is 2.1.22. ]

**Comment by KieranMigaku** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
