### ISSUE TITLE
Kifuku pattern hover breaks

### ISSUE THREAD

**Issue by Falab3lla** [migaku-official/Migaku-Japanese-Addon#60]
**Type:**
  - [X] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: MacOS 10.14.6 (18G5033)

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [X] no

**Description:**
I've encountered a bug with the pattern hover feature. From what I can tell, it's limited to the Kifuku pattern words. If the number is other than 1 (;k1), the hover pitch pattern doesn't show properly. I only get the pattern name and a tiny vertical line (kind of like a comma but completely straight) in the white space where the pattern usually shows, nothing else. I'm on Anki 2.1.23. The issue is limited to those patterns, the others are working perfectly.
![Capture d’écran, le 2020-07-12 à 20 11 05](https://user-images.githubusercontent.com/68208536/87261576-c2bb3f80-c484-11ea-9f0f-e35b0f1672ba.png)

**Comment by Seltralichan** [comment]
Same issue but what ElaxDev suggested doesn't work...

**Comment by KieranMigaku** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.

**Comment by HitogiDev** [comment]
It's still happening I have Anki 2.1.35 and the last version of the addon.

![image](https://user-images.githubusercontent.com/31047609/118719870-fa0e2180-b7f6-11eb-8e1e-304b37b4451e.png)

**Comment by archiif** [comment]
It's still happening for me in the latest version (Ver. 1.2.3) too.
