### ISSUE TITLE
MIA Japanese Add on causing Anki to crash - Sentence button

### ISSUE THREAD

**Issue by JoCa20** [migaku-official/Migaku-Japanese-Addon#64]
**Type:**
  - [ x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: windows

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x ] no

**Description:**
I have Anki Version 2.1.22 (0ecc189a).
When I click on the "sentence" button within a new card, it causes anki to freeze. I have to go to the task manager to manually end the program. I have tried may fixes: restarting the computer, uninstalling and then reinstalling, optimizing the database, forced one way sync. Nothing has helped. I would be happy to provide more information if requested. I hope someone has a fix they can recommend as this add on was working for ~2 weeks before it stopped.

**Comment by L-Chiki** [comment]
Same exact problem.
Anki 2.1.22 - Windows 10 (64-bit)
Reading and audio generation (F2 and F3) cause Anki to lock up.
Same behavior triggered when sending data from MIA Dictionary add-on if reading generation is turned on.

Reinstalling the add-on, reinstalling Anki, starting form new empty profile - none have any effect.

**Comment by KieranMigaku** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
