### ISSUE TITLE
Furigana rendering improperly

### ISSUE THREAD

**Issue by h3nnn4n** [migaku-official/Migaku-Japanese-Addon#67]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: MacOs Catalina 10.15.6 (19G2021),
  - Anki: Version 2.1.23 (de9543ff), Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
  - MIA Japaese Addon: Latest version from anki web.

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
`いま、レポートを 書[か]いています。後[あと]で 行[い]きます。」` causes a furigana to render improperly for `後`. It looks like `あと` is being applied over `いています。後` instead of just `後`. Perhaps the parser (not sure what it is called) is not considering `。` as a word boundary?  Adding a space after `。` solves the issue.

Here is a gif showing it happening: https://thumbs.gfycat.com/UntriedCalmAxisdeer-mobile.mp4

**Comment by KieranMigaku** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
