### ISSUE TITLE
入り込む has incorrect pitch accent information

### ISSUE THREAD

**Issue by bgx90** [migaku-official/Migaku-Japanese-Addon#68]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Debian Testing

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
Pitch accent information for the word 入り込む seems to be incorrect. The plugin gives the accent as `k3,o,h`, but according to the Sanseido Super Daijirin dictionary, the accent should be `k4,h`. The Kanjium pitch accent dictionary in Yomichan lists the same accents as the Sanseido dictionary. I could not find any dictionary that says that 入り込む can have 尾高 accent, so it may have it in some cases, but it seems to me that the 起伏 accent should definitely be on the fourth mora of the dictionary form and not the third.

**Comment by KieranMigaku** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.

**Comment by archiif** [comment]
This issue still persists in the latest version (Ver. 1.2.3), please do re-open this issue.
A possible cause to this issue is that it might be mixing up いりこむ and はいりこむ:
![](https://i.imgur.com/NiNpH3h.png)
