### ISSUE TITLE
Is it possible to auto-generate Readings/Accents/Audio?

### ISSUE THREAD

**Issue by eao** [migaku-official/Migaku-Japanese-Addon#72]
**Type:**
  - [ ] bug
  - [ ] feature
  - [ ] enhancement
  - [x] question

**Environment:**
  - OS: Win7/Win10 (use win7 laptop and win10 desktop)

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**

As title:  Is it possible to auto-generate Readings/Accents/Audio on a card being added to a specific deck rather than having to do it manually through Browse->Edit?  For the cards in my main sentence deck, after an adding session I go to Browse->Edit->Generate Readings/Accents/Audio, change Origin to "Sentence" (one of my arbitrarily named fields) and destination to "Expression" (another one of my arbitrarily named fields) then hit Execute.

I have to do this manually for each card added, although of course I can do them in bulk after an adding session.  I was wondering, is there a way to automate this process being done at the time a new card is added, rather than having to do it manually afterwards?

BTW, thank you so much for your work on this addon, it is amazing.

**Comment by KieranMigaku** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
